<?php
/**
 * Template Name: Ranked Intl: Turf & Tree Service
 *
 * A WordPress-native version of the paid traffic landing page. The active
 * theme continues to own the header, navigation, footer, and WordPress form.
 */

get_header();

$case_study_url = home_url( '/case-studies/turf-and-design/' );
?>

<main id="top" class="trade-landing">
  <section class="hero trade-hero" id="hero">
    <div class="hero__bg" aria-hidden="true"><div class="hero__aurora"></div><div class="hero__grain"></div></div>
    <div class="hero__inner">
      <div class="hero__copy">
        <div class="hero__card">
          <div class="hero__text-block">
            <p class="hero__eyebrow">SEO FOR TURF, TREE CARE &amp; OUTDOOR SERVICES</p>
            <h1 class="hero__title">Show up <em>first</em> on Google and get the calls.</h1>
            <p class="hero__sub">We get turf, tree service and outdoor businesses to the top of Google and Google Maps, so your phone rings with ready-to-buy customers.</p>
          </div>
          <div class="hero__bottom trade-hero__actions">
            <a href="#audit" class="btn btn--primary btn--lg" data-track="hero-audit">Get free SEO audit</a>
            <a href="#case-study" class="btn btn--ghost-light">See the turf case study</a>
          </div>
          <div class="hero__stats">
            <div class="hero__stat"><span class="trade-icon" aria-hidden="true">⌕</span><div class="hero__stat-text"><strong>Google + Google Maps</strong><span>where ready-to-buy customers search</span></div></div>
            <div class="hero__stat"><span class="trade-icon" aria-hidden="true">✓</span><div class="hero__stat-text"><strong>Month to month</strong><span>no long-term contract</span></div></div>
          </div>
        </div>
      </div>
      <div class="hero__visual trade-hero__visual" aria-label="Verified ranking snapshot for TX Artificial Turf and Design">
        <div class="rank-panel">
          <div class="rank-panel__head"><div><p class="rank-panel__label">LIVE RESULTS OF A CLIENT</p><h2>TX Artificial Turf &amp; Design</h2></div><img src="<?php echo rip_asset( 'brand-logos/9.png' ); ?>" alt="TX Artificial Turf and Design" width="150" height="42"></div>
          <p class="rank-panel__search"><span aria-hidden="true">⌕</span> What local customers are searching</p>
          <ol class="rank-panel__rows"><li><span><b>turf company dallas</b><small>Dallas, TX</small></span><strong>#1</strong></li><li><span><b>dallas turf company</b><small>Dallas, TX</small></span><strong>#1</strong></li><li><span><b>richardson turf company</b><small>Richardson, TX</small></span><strong>#1</strong></li><li><span><b>turf company plano</b><small>Plano, TX</small></span><strong>#2</strong></li></ol>
          <p class="rank-panel__source">✓ Verified project case-study data</p>
        </div>
      </div>
    </div>
  </section>

  <section class="promise trade-promise" id="promise"><div class="promise__inner"><p class="promise__tag">THE REAL PROBLEM</p><div class="promise__statement"><p>Great work means nothing if nobody can <span class="hl">find you.</span></p><p>You could be the best in town, but if you are buried on <span class="hl">page three</span>, the jobs go to whoever shows up first.</p></div></div></section>

  <section class="trade-case" id="case-study"><div class="trade-case__inner"><header class="section-head trade-case__head"><p class="eyebrow"><span class="dot"></span>Featured turf case study</p><h2 class="section-title">From zero traffic to <em>Domain Authority 55.</em></h2></header><div class="trade-case__layout"><blockquote class="trade-case__quote"><img src="<?php echo rip_asset( 'brand-logos/9.png' ); ?>" alt="TX Artificial Turf and Design" width="190" height="54"><p>Dedicated city pages for Richardson, Plano, Frisco and Fort Worth, backed by sustained link building, created the authority to compete across DFW.</p><a href="<?php echo esc_url( $case_study_url ); ?>" class="trade-case__link">See the complete case study <span aria-hidden="true">↗</span></a></blockquote><div class="trade-case__proof"><div class="trade-case__keyword-card"><p class="trade-case__kicker">RANKING PROOF</p><h3>Four city pages. One stronger domain.</h3><div class="keyword-locations"><span>Dallas</span><span>Richardson</span><span>Plano</span><span>Fort Worth</span></div><dl><div><dt>Domain Authority</dt><dd>55</dd></div><div><dt>Ranking keywords</dt><dd>275</dd></div><div><dt>Backlinks earned</dt><dd>4,400+</dd></div></dl></div><div class="trade-case__metrics"><div class="cs__metric-block"><p class="cs__metric-label">Monthly organic visitors</p><p class="cs__metric-num">221</p><p class="cs__metric-sub">Up from zero after the 18-month breakout.</p></div><div class="cs__metric-block"><p class="cs__metric-label">#1 Google rankings</p><p class="cs__metric-num">5</p><p class="cs__metric-sub">Including Dallas and Richardson turf terms.</p></div></div></div></div></div></section>

  <section class="audit-preview"><div class="audit-preview__inner"><header class="section-head"><h2 class="section-title">In your free audit, see exactly where you <em>rank.</em></h2></header><div class="audit-deliverables"><article><span>01</span><div><h3>Keyword gaps</h3><p>See searches you should rank for but do not yet own.</p></div></article><article><span>02</span><div><h3>Google Maps</h3><p>See how your listing looks to local customers right now.</p></div></article><article><span>03</span><div><h3>Clear plan</h3><p>Get the three biggest fixes and a realistic timeline.</p></div></article></div></div></section>

  <section class="trade-commitments"><div class="trade-commitments__inner"><header class="section-head"><h2 class="section-title">SEO done right and done <em>honestly.</em></h2></header><ul class="trade-commitments__list" aria-label="Our commitments"><li><span>01</span><img class="trade-commitments__art" src="<?php echo rip_asset( 'commitments/month-to-month.png' ); ?>" alt="Illustration of a flexible agreement and calendar" loading="lazy" decoding="async"><div class="trade-commitments__copy"><strong>Stay by choice</strong><p>No lock-in contracts. If the work is not bringing results, you are free to leave.</p></div></li><li><span>02</span><img class="trade-commitments__art" src="<?php echo rip_asset( 'commitments/map-organic.png' ); ?>" alt="Illustration of a map and search results working together" loading="lazy" decoding="async"><div class="trade-commitments__copy"><strong>Win the map</strong><p>Show up on Google Maps, where the near-me calls actually happen.</p></div></li><li><span>03</span><img class="trade-commitments__art" src="<?php echo rip_asset( 'commitments/search-coverage.png' ); ?>" alt="Illustration of connected local search coverage" loading="lazy" decoding="async"><div class="trade-commitments__copy"><strong>Cast a keyword net</strong><p>Cover every way your customers search, not just three or four keywords.</p></div></li><li><span>04</span><img class="trade-commitments__art" src="<?php echo rip_asset( 'commitments/asset-ownership.png' ); ?>" alt="Illustration of client-owned digital assets" loading="lazy" decoding="async"><div class="trade-commitments__copy"><strong>Keep ownership</strong><p>Your website, profiles, content and accounts remain yours.</p></div></li><li><span>05</span><img class="trade-commitments__art" src="<?php echo rip_asset( 'commitments/plain-reporting.png' ); ?>" alt="Illustration of a clear performance report" loading="lazy" decoding="async"><div class="trade-commitments__copy"><strong>Keep it transparent</strong><p>Know what we are doing, which keywords we are chasing and where you rank.</p></div></li><li><span>06</span><img class="trade-commitments__art" src="<?php echo rip_asset( 'commitments/honest-timeline.png' ); ?>" alt="Illustration of steady growth over time" loading="lazy" decoding="async"><div class="trade-commitments__copy"><strong>Set honest expectations</strong><p>No fake page-one promises, just straight talk and durable results.</p></div></li></ul></div></section>

  <section class="trade-fit"><div class="trade-fit__inner"><div class="trade-fit__columns"><article><p class="trade-fit__label">WHO WE’RE BUILT FOR</p><h3>You have a real operation and room for more work.</h3><ul><li>Defined cities and service areas</li><li>A verified business and functioning website</li><li>Capacity to answer and fulfill more leads</li><li>Patience for compounding search growth</li></ul></article><article><p class="trade-fit__label">WHEN THIS WON’T WORK</p><h3>You need an overnight switch, not a growth system.</h3><ul><li>A guarantee of page one in 30 days</li><li>No budget to improve the website</li><li>No way to track or answer incoming calls</li><li>Service areas you cannot reliably cover</li></ul></article></div></div></section>

  <section class="trade-comparison" aria-labelledby="comparison-title"><div class="trade-comparison__inner"><header class="section-head"><p class="eyebrow"><span class="dot"></span>The honest comparison</p><h2 class="section-title" id="comparison-title">Ranked International vs. a typical <em>SEO agency.</em></h2></header><div class="trade-comparison__scroll" tabindex="0"><table class="trade-comparison__table"><thead><tr><th scope="col">What matters</th><th scope="col">Typical agency</th><th scope="col">Ranked International</th></tr></thead><tbody><tr><th scope="row">Long-term contract</th><td>6 to 12 month lock-in</td><td>None. Stay by choice.</td></tr><tr><th scope="row">Keywords targeted</th><td>Just 3 to 4</td><td>A full net of 20 to 30</td></tr><tr><th scope="row">Google Maps visibility</th><td>Often ignored</td><td>Built in</td></tr><tr><th scope="row">Transparency</th><td>Confusing reports</td><td>Plain English, always</td></tr><tr><th scope="row">Honest timelines</th><td>Fast page-one promises</td><td>Straight talk and results that last</td></tr></tbody></table></div></div></section>

  <section class="faq trade-faq" id="faq"><div class="faq__head"><p class="eyebrow"><span class="dot"></span>Common questions</p><h2>What business owners ask us.</h2></div><div class="trade-faq__layout"><nav class="trade-faq__topics" aria-label="FAQ topics"><a href="#faq-engagement" class="is-active">Engagement</a><a href="#faq-results">Results</a><a href="#faq-ownership">Ownership</a><a href="#faq-audit">Audit</a></nav><div class="faq__list"><p class="trade-faq__group" id="faq-engagement">Engagement</p><article class="faq__item is-open"><button class="faq__question" type="button" aria-expanded="true"><span>Do I have to sign a long-term contract?</span><span aria-hidden="true">+</span></button><div class="faq__answer"><p>No. You stay month to month because the work is bringing results. If it is not, you are free to leave.</p></div></article><article class="faq__item"><button class="faq__question" type="button" aria-expanded="false"><span>How is pricing determined?</span><span aria-hidden="true">+</span></button><div class="faq__answer"><p>Pricing depends on services, locations, competition and website work. The audit establishes scope before a proposal.</p></div></article><p class="trade-faq__group" id="faq-results">Results</p><article class="faq__item"><button class="faq__question" type="button" aria-expanded="false"><span>How quickly should I expect results?</span><span aria-hidden="true">+</span></button><div class="faq__answer"><p>SEO is not overnight. Early movement can begin in months and compounds over time.</p></div></article><article class="faq__item"><button class="faq__question" type="button" aria-expanded="false"><span>Can you target every city we serve?</span><span aria-hidden="true">+</span></button><div class="faq__answer"><p>We prioritize cities you can genuinely cover, then build useful service-area pages where the opportunity supports them.</p></div></article><p class="trade-faq__group" id="faq-ownership">Ownership</p><article class="faq__item"><button class="faq__question" type="button" aria-expanded="false"><span>Who owns the website, content and accounts?</span><span aria-hidden="true">+</span></button><div class="faq__answer"><p>You do. We work through client-owned properties so the business retains its assets if the engagement ends.</p></div></article><p class="trade-faq__group" id="faq-audit">Audit</p><article class="faq__item"><button class="faq__question" type="button" aria-expanded="false"><span>What is included in the free audit?</span><span aria-hidden="true">+</span></button><div class="faq__answer"><p>Where you rank, the keywords you are missing, how your Maps profile appears, and the biggest fixes to get you climbing.</p></div></article></div></div></section>

  <section class="cta" id="cta-final"><div class="cta__inner"><div class="cta__copy"><p class="cta__title">Stop losing customers to businesses with worse work and better <em>rankings.</em></p><p class="cta__sub">Every month you are invisible on Google is a month of jobs going to someone else. Let’s fix that.</p></div><div class="trade-cta__actions"><a href="#audit" class="btn btn--dark btn--lg" data-track="final-audit">Get free SEO audit</a><span>No contract. No obligation.</span></div></div></section>
</main>

<a href="#audit" class="mobile-sticky-audit" data-track="mobile-sticky-audit">Get free SEO audit <span aria-hidden="true">→</span></a>

<?php rip_render_audit_modal(); ?>
<?php get_footer(); ?>
